name: Documentation Review

on:
  pull_request:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to get changes between commits

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"  # Or any version you want

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install PyGithub  # For interacting with GitHub API
          # Install any other dependencies, including google-ai-gemini if available

      - name: Run Gemini evaluation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} # Store your Gemini API key as a secret
        run: python .github/scripts/evaluate_docs.py  # Path to your script